[package]
name = "tree-sitter-scss"
description = "Tree-sitter parser for SCSS and CSS"
version = "1.0.1"
keywords = ["tree-sitter", "parser", "css", "scss", "sass"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/P233/tree-sitter-scss"
edition = "2024"
license = "MIT"
publish = false
readme = "README.md"
build = "bindings/rust/build.rs"
include = ["/bindings/rust/*", "/grammar.js", "/queries/*", "/src/**", "/tree-sitter.json", "/README.md", "/LICENSE"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1.8"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.27.0"
